version: 2
updates:
  - package-ecosystem: maven
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    pull-request-branch-name:
      separator: "_"
    ignore:
      - dependency-name: org.apache.maven.plugins:maven-compiler-plugin

  # Dependencies for the rhbq-2.7 branch
  - package-ecosystem: maven
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    target-branch: rhbq-2.7
    pull-request-branch-name:
      separator: "_"
    ignore:
      - dependency-name: org.apache.maven.plugins:maven-compiler-plugin

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    pull-request-branch-name:
      separator: "_"

  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    target-branch: rhbq-2.7
    pull-request-branch-name:
      separator: "_"

  #--------- for Pact branch ------------
  - package-ecosystem: maven
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    target-branch: pact
    pull-request-branch-name:
      separator: "_"
    ignore:
      - dependency-name: org.apache.maven.plugins:maven-compiler-plugin

  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    target-branch: pact
    pull-request-branch-name:
      separator: "_"
