name: Basic build and test

on:
  push:
    paths-ignore:
      - '**/deploy/**'
      - '**/*.md'
      - 'docs/**'
      - '**/images/**'
      - '.github/dependabot.yml'
      - '.github/quarkus-ecosystem-test'
      - '.github/workflows/quarkus-snapshot.yaml'
      - '.github/workflows/build-push-ui-images.yml'
      - '.github/workflows/dependabot-automerge.yml'
      - 'scripts/deploy-to-azure-containerapps.sh'
      - 'scripts/watch-services.sh'
      - '**/hyperfoil/**'
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
    paths-ignore:
      - '**/deploy/**'
      - '**/*.md'
      - 'docs/**'
      - '**/images/**'
      - '.github/dependabot.yml'
      - '.github/build-push-container-images*.yml'
      - '.github/quarkus-ecosystem-test'
      - '.github/workflows/quarkus-snapshot.yaml'
      - '.github/workflows/build-push-ui-images.yml'
      - '.github/workflows/dependabot-automerge.yml'
      - 'scripts/*.sh'
      - '**/hyperfoil/**'
  workflow_dispatch:

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  jvm-build-test:
    runs-on: ubuntu-latest
    if: github.repository == 'quarkusio/quarkus-super-heroes'
    strategy:
      fail-fast: false
      matrix:
        java:
          - '17'
          - '21'
        project:
          - event-statistics
          - rest-fights
          - rest-heroes
          - rest-villains
          - rest-narration
          - grpc-locations
          - ui-super-heroes
    name: "build-test-${{ matrix.project }}-${{ matrix.java }}"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven

      - name: "build-test-jvm-${{ matrix.project }}-java-${{ matrix.java }}"
        working-directory: ${{ matrix.project }}
        run: |
          ./mvnw -B clean verify \
            -Dquarkus.http.host=0.0.0.0 \
            -Dmaven.compiler.release=${{ matrix.java }} 

  native-build-test:
    runs-on: ubuntu-latest
    if: github.repository == 'quarkusio/quarkus-super-heroes'
    strategy:
      fail-fast: false
      matrix:
        java:
          - { graal: '23.1.1.0', java: '21'}
        project:
          - event-statistics
          - rest-fights
          - rest-heroes
          - rest-villains
# Until https://github.com/microsoft/semantic-kernel/issues/2885 is resolved
#          - rest-narration
          - grpc-locations
          - ui-super-heroes
    name: "native-build-test-${{ matrix.project }}"
    steps:
      - uses: actions/checkout@v4

      - name: Cache and restore GraalVM CE (${{ matrix.java.graal }})
        id: check-graal-cache
        uses: actions/cache@v3
        with:
          path: mandrel-java${{ matrix.java.java}}-linux-amd64-${{ matrix.java.graal }}-Final.tar.gz
          key: mandrel-distro-${{ matrix.java.graal }}

      - name: Download GraalVM CE ${{ matrix.java.graal }}
        if: steps.check-graal-cache.outputs.cache-hit != 'true'
        run: |
          download_url="https://github.com/graalvm/mandrel/releases/download/mandrel-${{ matrix.java.graal }}-Final/mandrel-java${{ matrix.java.java }}-linux-amd64-${{ matrix.java.graal }}-Final.tar.gz"
          wget -q -O mandrel-java${{ matrix.java.java }}-linux-amd64-${{ matrix.java.graal }}-Final.tar.gz $download_url

      - name: Setup GraalVM CE ${{ matrix.java.graal }} distro
        uses: actions/setup-java@v3
        with:
          distribution: 'jdkfile'
          jdkFile: mandrel-java${{ matrix.java.java }}-linux-amd64-${{ matrix.java.graal }}-Final.tar.gz
          java-version: ${{ matrix.java.java }}
          architecture: x64
          cache: maven

      - name: "build-test-native-${{ matrix.project }}-java-${{ matrix.java.java }}"
        working-directory: ${{ matrix.project }}
        run: |
          ./mvnw -B clean verify -Pnative \
            -Dquarkus.http.host=0.0.0.0 \
            -Dmaven.compiler.release=${{ matrix.java.java }} 
  
