name: Test matrix

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - '17'
        project:
          - event-statistics
          - rest-fights
          - rest-heroes
          - rest-villains
          - rest-narration
          - grpc-locations
          - ui-super-heroes
        openai-type:
          - openai
          - azure-openai
          - ""
        exclude:
          - project: event-statistics
            openai-type: openai
          - project: event-statistics
            openai-type: azure-openai
          - project: rest-fights
            openai-type: openai
          - project: rest-fights
            openai-type: azure-openai
          - project: rest-heroes
            openai-type: openai
          - project: rest-heroes
            openai-type: azure-openai
          - project: rest-villains
            openai-type: openai
          - project: rest-villains
            openai-type: azure-openai
          - project: grpc-locations
            openai-type: openai
          - project: grpc-locations
            openai-type: azure-openai
          - project: ui-super-heroes
            openai-type: openai
          - project: ui-super-heroes
            openai-type: azure-openai
          - project: rest-narration
            openai-type: ""
    name: "build-test-${{ matrix.project }}-${{ matrix.java }}-${{ matrix.openai-type }}"
    steps:
      - uses: actions/checkout@v4

      - name: Show common
        run: echo "Running for project = ${{ matrix.project }} and java = ${{ matrix.java }}"

      - name: Show specific
        if: matrix.openai-type
        run: echo "Project = ${{ matrix.project }}, java = ${{ matrix.java }}, openai-type = ${{ matrix.openai-type }}"
