name: Test matrix

on:
  workflow_dispatch:

jobs:
  another-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - '17'
        kind:
          - ""
          - 'native-'
        project:
          - { name: rest-narration, openai-types: ['openai','azure-openai'] }
    name: "Create app multiarch manifests (${{ matrix.project.name }}-${{ matrix.kind }}java${{ matrix.java }}-${{ matrix.project.openai-types }})"
    steps:
      - name: Print stuff
        run: |
          echo "java = ${{ matrix.java }}, kind = ${{ matrix.kind }}, project = ${{ matrix.project.name }}"

          for t in ${openai-types[@]}; do
            echo "openai-type = $t"
          done

  # test:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       java:
  #         - '17'
  #       arch:
  #         - amd64
  #         - arm64
  #       project:
  #         - { name: event-statistics }
  #         - { name: rest-fights }
  #         - { name: rest-heroes }
  #         - { name: rest-villains }
  #         - { name: rest-narration, openai-type: openai }
  #         - { name: rest-narration, openai-type: azure-openai }
  #         - { name: grpc-locations }
  #         - { name: ui-super-heroes }
  #   name: "[${{ matrix.arch }}] - build-test-${{ matrix.project.name }}-${{ matrix.java }}-${{ matrix.project.openai-type }}"
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Show common
  #       if: matrix.project.openai-type == ''
  #       run: echo "arch = ${{ matrix.arch }}, project = ${{ matrix.project.name }}, java = ${{ matrix.java }}"

  #     - name: Show specific
  #       if: matrix.project.openai-type
  #       run: echo "arch = ${{ matrix.arch }}, project = ${{ matrix.project.name }}, java = ${{ matrix.java }}, openai-type = ${{ matrix.project.openai-type }}"
