name: Test matrix

on:
  workflow_dispatch:

jobs:
  another-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - '17'
        kind:
          - ""
          - 'native-'
        project:
          - rest-narration
    name: "Create app multiarch manifests (${{ matrix.project }}-${{ matrix.kind }}java${{ matrix.java }})"
    steps:
      - name: Stuff
        shell: bash
        run: |
          openai_types=("openai" "azure-openai")
          platforms=("linux/amd64" "linux/arm64")
          
          for openaiType in "${openai_types[@]}"
          do
            openai_type_container_tag="${{ env.CONTAINER_TAG }}-${openaiType}"
            openai_type_additional_tag="${{ env.ADDITIONAL_TAG }}-${openaiType}"
          
            for platform in "${platforms[@]}"
            do
              echo "docker pull --platform $platform ${{ env.IMAGE_BASE_NAME }}/${{ matrix.project }}:$openai_type_container_tag"
              echo "docker pull --platform $platform ${{ env.IMAGE_BASE_NAME }}/${{ matrix.project }}:$openai_type_additional_tag"
            done
          
            echo "docker tag ${{ env.IMAGE_BASE_NAME }}/${{ matrix.project }}:$openai_type_container_tag ${{ env.IMAGE_BASE_NAME }}/${{ matrix.project }}:${{ env.CONTAINER_TAG }}"
            echo "docker tag ${{ env.IMAGE_BASE_NAME }}/${{ matrix.project }}:$openai_type_additional_tag ${{ env.IMAGE_BASE_NAME }}/${{ matrix.project }}:${{ env.ADDITIONAL_TAG }}"
          done
          
          echo "docker push -a ${{ env.IMAGE_BASE_NAME }}/${{ matrix.project }}"

  # test:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       java:
  #         - '17'
  #       arch:
  #         - amd64
  #         - arm64
  #       project:
  #         - { name: event-statistics }
  #         - { name: rest-fights }
  #         - { name: rest-heroes }
  #         - { name: rest-villains }
  #         - { name: rest-narration, openai-type: openai }
  #         - { name: rest-narration, openai-type: azure-openai }
  #         - { name: grpc-locations }
  #         - { name: ui-super-heroes }
  #   name: "[${{ matrix.arch }}] - build-test-${{ matrix.project.name }}-${{ matrix.java }}-${{ matrix.project.openai-type }}"
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Show common
  #       if: matrix.project.openai-type == ''
  #       run: echo "arch = ${{ matrix.arch }}, project = ${{ matrix.project.name }}, java = ${{ matrix.java }}"

  #     - name: Show specific
  #       if: matrix.project.openai-type
  #       run: echo "arch = ${{ matrix.arch }}, project = ${{ matrix.project.name }}, java = ${{ matrix.java }}, openai-type = ${{ matrix.project.openai-type }}"
